[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "day01"
path = "src/bin/day01.rs"

[[bin]]
name = "day02"
path = "src/bin/day02.rs"

# Add more days as needed
